from dataclasses import dataclass
from win32con import HS_BDIAGONAL, HS_CROSS, HS_FDIAGONAL, HS_HORIZONTAL, HS_VERTICAL, HS_DIAGCROSS

@dataclass
class Hatch:
    DCROSS = HS_DIAGCROSS
    UDIAG = HS_BDIAGONAL
    DDIAG = HS_FDIAGONAL
    HORIZONTAL = HS_HORIZONTAL
    VERTICAL = HS_VERTICAL
    CROSS = HS_CROSS

